### ISSUE TITLE
I can't find these document.

### ISSUE THREAD

**Issue by nana-zhang** [ins-amu/BVEP#2]
![8587b88c681a1e1fc4af0315447cd47](https://user-images.githubusercontent.com/70929994/142344443-b72c7550-ea4f-43d0-80b2-1a0497e06842.png)
![facc6e3d9fd9f16b627aaa19f4e9c96](https://user-images.githubusercontent.com/70929994/142344461-c9d3e21d-236a-4a93-a25f-e6e9925371ea.png)
![e92581e59626e936d3f4b48b69b39f8](https://user-images.githubusercontent.com/70929994/142344479-30dbb89b-46d7-4d5b-8b59-a217e269a1fa.png)
![fecdcf5db9e7243f2c3d2998b156f4c](https://user-images.githubusercontent.com/70929994/142344485-73e00968-d2da-4f37-98bd-0046edc08153.png)
Hello,Hello, I'd like to ask where these documents are. I can't find them.Are these documents not public?

**Comment by maedoc** [comment]
These are clinical data for a patient and cannot be made public. Sorry for the inconvenience.
